ALTER TABLE "Hospital" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TranslationRoom" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RoomParticipant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UsageSession" ENABLE ROW LEVEL SECURITY;
