import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { verifiedSentenceSpecialtySeedEntries } from "../src/lib/verified-sentence-seed";

const outputPath = resolve(
  "android-staff-app/app/src/main/java/com/clinicvoiceroom/staff/OfflineVerifiedPhrases.kt"
);

function kotlinString(value: string) {
  return `"${value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")}"`;
}

const specialtyLabels: Record<string, string> = {
  dermatology: "피부과",
  plastic_surgery: "성형외과"
};

const phraseRows = verifiedSentenceSpecialtySeedEntries.map((entry, index) => {
  const translations = Object.entries(entry.translations)
    .map(([language, text]) => `            ${kotlinString(language)} to ${kotlinString(text)}`)
    .join(",\n");
  const specialty = entry.specialty ? kotlinString(entry.specialty) : "null";
  return `    OfflineVerifiedPhrase(
        id = ${kotlinString(`VERIFIED_${String(index + 1).padStart(3, "0")}`)},
        specialty = ${specialty},
        specialtyLabel = ${kotlinString(entry.specialty ? specialtyLabels[entry.specialty] ?? entry.specialty : "공통")},
        category = ${kotlinString(entry.category)},
        korean = ${kotlinString(entry.standardKo)},
        translations = mapOf(
${translations}
        )
    )`;
}).join(",\n");

const source = `// Generated by scripts/generate-android-verified-phrases.ts. Do not edit manually.
package com.clinicvoiceroom.staff

data class OfflineVerifiedPhrase(
    val id: String,
    val specialty: String?,
    val specialtyLabel: String,
    val category: String,
    val korean: String,
    val translations: Map<String, String>
) {
    fun translated(language: String): String? = translations[language]
}

val offlineVerifiedPhrases = listOf(
${phraseRows}
)
`;

async function main() {
  await writeFile(outputPath, source, "utf8");
  console.log(`Generated ${verifiedSentenceSpecialtySeedEntries.length} reviewed phrases at ${outputPath}`);
}

void main();
